### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by orltom**
to avoid umask issues, change ownership inside the data-pod

### CODE REVIEW

**Review by libuweber — CHANGES_REQUESTED** [review]
The change also needs to be made in the deploy.sh that is used for deploying the example to a kind cluster in the PR workflow.

**Comment by orltom** [comment]
> The change also needs to be made in the deploy.sh that is used for deploying the example to a kind cluster in the PR workflow.

good point,

**Comment by orltom** [comment]
@libuweber 
> The change also needs to be made in the deploy.sh that is used for deploying the example to a kind cluster in the PR workflow.
good point and Done :)

**Review by jubeergon — APPROVED** [review]
Looks good to me.

**Pull request merged**
